spring.application.name=springassignments

spring.datasource.url=jdbc:mysql://localhost:3306/learning?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

# Disable default Security password for dev (optional)
spring.security.user.name=admin
spring.security.user.password=P@ssw0rd

# For development (Angular default port)
app.cors.allowed-origins=http://localhost:4200